//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmPark.Integration.External.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACD_CustomerSession
    {
        public System.Guid SessionID { get; set; }
        public string CustomerID { get; set; }
        public string SessionType { get; set; }
        public System.Guid QueueID { get; set; }
        public int SessionNumber { get; set; }
        public Nullable<System.DateTime> SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
        public string Properties { get; set; }
        public string Address { get; set; }
        public int HostNumber { get; set; }
        public int Priority { get; set; }
        public Nullable<double> RestoreOrder { get; set; }
        public Nullable<System.DateTime> ActivationTime { get; set; }
    }
}
