//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmPark.Integration.LinkMegafonToMightyCall.DbDataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV_CallRecord
    {
        public int pkID { get; set; }
        public string OrgName { get; set; }
        public string OrgNumber { get; set; }
        public string OrgLine { get; set; }
        public string DestName { get; set; }
        public string DestNumber { get; set; }
        public string DestLine { get; set; }
        public System.DateTime StartTime { get; set; }
        public byte Direction { get; set; }
        public int Duration { get; set; }
        public string MediaFileName { get; set; }
        public string RawParty { get; set; }
        public string Read { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> SessionID { get; set; }
        public Nullable<int> fkFolder { get; set; }
        public Nullable<long> FileSize { get; set; }
        public byte Importance { get; set; }
        public Nullable<System.Guid> QueueID { get; set; }
    }
}
