//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmPark.Integration.LinkMegafonToMightyCall.DbDataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Megafon_calls
    {
        public string call_id { get; set; }
        public string call_type { get; set; }
        public string call_status { get; set; }
        public string client { get; set; }
        public string diversion { get; set; }
        public string destination { get; set; }
        public string user_login { get; set; }
        public string user_name { get; set; }
        public string group_name { get; set; }
        public string start { get; set; }
        public Nullable<int> wait { get; set; }
        public Nullable<int> duration { get; set; }
        public string record { get; set; }
        public string record_path { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<bool> is_processed { get; set; }
        public Nullable<System.Guid> call_external_id { get; set; }
        public Nullable<System.Guid> call_guid_crm { get; set; }
        public Nullable<bool> is_processed_crm { get; set; }
        public bool is_external { get; set; }
        public Nullable<System.Guid> account_id { get; set; }
    }
}
